version: "3.8"
services:
  api:
    build:
      context: ./apollo-server-trial-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./apollo-server-trial-api/src:/usr/app/src
      - ~/.aws:/root/.aws
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://postgres:5432
      - -wait-retry-interval
      - 5s
    command: [ "yarn","dev" ]
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
